#
# note
# if terraform state gets locked, delete DynamoDB lock rows
#

name: CI - Integration Tests - Cleanup
on:
  workflow_dispatch

concurrency: terraform
jobs:
  test_cleanup:
    name: Test Cleanup
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_project_id: ${{secrets.GCP_DRAIOS_PROJECT_ID}}
      TF_VAR_sysdig_secure_api_token: ${{secrets.KUBELAB_SECURE_API_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_DRAIOS_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_DRAIOS_SA_KEY }}
          export_default_credentials: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Destroy resources
        run: bundle exec kitchen destroy
